# Generated by Django 4.2.3 on 2023-07-11 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
                ('tipoU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipo_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('keyMaster', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now=True, verbose_name='%d/%m/%Y')),
                ('Usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
                ('tipoC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipo_contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now=True)),
                ('valoracion', models.PositiveIntegerField(default=0)),
                ('Usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
                ('cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contenido')),
            ],
        ),
    ]
